config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users

  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :book
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one :author, dependent: :destroy
  belongs_to :user
  validates_presence_of :name
  accepts_nested_attributes_for :author
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :books
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end

  def logged_in?
    current_user != nil
  end

end

app/controllers/books_controller.rb
class BooksController <  ApplicationController
  before_action :authenticate_user!
  before_filter :load_book, except: [:index, :new]

  def index
    @books = current_user.books
  end

  def new
    @book = Book.new(:author=>Author.new)
  end

  def create
    @book = Book.new(book_params.merge({user: current_user}))
    @book.build_author(author_params)
    render :new and return unless @book.save
    redirect_to books_path
  end

  def update
    render :edit and return unless @book.update(book_params.merge({author_attributes: author_params}))
    redirect_to books_path
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def author_params
    params.require(:book).permit(author: [:name])[:author]
  end

  def book_params
    params.require(:book).permit(:name, :year, :isbn)
  end

  def load_book
    @book = current_user.books.find(params[:id])
    @book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= @book.errors.full_messages.to_sentence-%>
<h1>Create a new book</h1>
<%= form_for @book, url: { action: action } do |f| %>
  Name: <%= f.text_field :name %>
  <%= f.fields_for @book.author  do |author| -%>
    Author:<%= author.text_field :name %>
  <% end -%>
  Year: <%= f.date_field :year %>
  ISBN: <%= f.number_field :isbn %>

  <%= submit_tag action.capitalize %>
<% end %>

app/views/books/edit.html.erb
<%= render partial: "form", locals: {action: "update"} %>

app/views/books/index.html.erb
<%= form_tag destroy_user_session_path, method: :delete do -%>
<%= submit_tag "Sign Out" -%>
<% end %>
<h1>List of all Books</h1>
<% @books.each do |book| -%>
  <%= link_to book.name, book_path(book) -%></div><br>
<% end -%>
<%= link_to "Create", new_book_path -%></div><br>

app/views/books/new.html.erb
<%= render partial: "form", locals: {action: "create"} %>

app/views/books/show.html.erb
<div> Name:
<%= @book.name -%>
  </div>
<div>
  <%= image_tag 'person.png', {class: 'person-icon'}-%>
  <%= @book.author.name -%>
</div>
<div> Year:
  <%= @book.year -%>
</div>
<div> ISBN:
  <%= @book.isbn -%>
</div>
<br>
<%= link_to "Back", books_path %>
<%= link_to "Edit", edit_book_path(@book) %>
<%= form_for @book, method: :delete  do |f| %>
    <%= submit_tag "Delete" %>
<% end %>

app/views/layouts/_nav.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <div class="col-xs-4">
        <%= link_to "NaanuOduvaBooks", root_path, id: "logo" %>
      </div>
      <div class="col-xs-4">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
              <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
          <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>-->
  <%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>